### ISSUE TITLE
Cannot run example script on latest version of deno

### ISSUE THREAD

**Issue by metruzanca** [Caesar2011/denotrain#3]
Running the example script has this result:
```
Compile https://deno.land/x/denotrain@v0.2.0/mod.ts
error: Uncaught TypeError: Cannot resolve extension for "https://raw.githubusercontent.com/jshttp/mime-db/master/db.json" with mediaType "Json".
    at getExtension ($deno$/compiler.ts:218:13)
    at new SourceFile ($deno$/compiler.ts:263:22)
    at Function.addToCache ($deno$/compiler.ts:339:16)
    at processImports ($deno$/compiler.ts:743:31)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async compile ($deno$/compiler.ts:1316:31)
```
Initially ran it inside a ts file and so added any types. I tried running this as a js file as well.
Very unfamiliar with deno, sorry if this is a deno issue and not a denotrain issue.

EDIT: Running on WSL1

**Comment by Caesar2011** [comment]
Try to use version v0.3.1 instead of 0.2.0

**Comment by liamnewmarch** [comment]
I get the same error on v0.2.0 after copying the example. Using v0.3.1 as mentioned above I get a different error:

```
$ deno run -Ar train.ts
Compile file:///[snip]/train.ts
Download https://deno.land/x/denotrain@v0.3.1/mod.ts
Download https://deno.land/x/denotrain@v0.3.1/Application.ts
Download https://deno.land/x/denotrain@v0.3.1/Router.ts
Download https://deno.land/x/denotrain@v0.3.1/Context.ts
Download https://deno.land/x/denotrain@v0.3.1/ViewEngine.ts
Download https://deno.land/x/denotrain@v0.3.1/ClientError.ts
Download https://deno.land/x/denotrain@v0.3.1/Response.ts
Download https://deno.land/x/denotrain@v0.3.1/Request.ts
Download https://deno.land/x/denotrain@v0.3.1/utils/object.ts
Download https://deno.land/x/denotrain@v0.3.1/deps.ts
Download https://deno.land/std@v1.0.0-rc1/http/server.ts
Download https://deno.land/std@v1.0.0-rc1/fs/read_file_str.ts
Download https://deno.land/std@v1.0.0-rc1/path/mod.ts
Download https://deno.land/x/media_types@v2.0.0/mod.ts
error: Uncaught Error: Import 'https://deno.land/std@v1.0.0-rc1/path/mod.ts' failed: 404 Not Found
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async processImports ($deno$/compiler.ts:736:23)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async compile ($deno$/compiler.ts:1316:31)
    at async tsCompilerOnMessage ($deno$/compiler.ts:1548:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:74:9)
```

**Comment by kentico-ericd** [comment]
I get the same error on 0.3.1:

> error: Uncaught TypeError: Cannot resolve extension for "https://raw.githubusercontent.com/jshttp/mime-db/master/db.json" with mediaType "Json".
    at getExtension ($deno$/compiler.ts:218:13)
    at new SourceFile ($deno$/compiler.ts:263:22)
    at Function.addToCache ($deno$/compiler.ts:339:16)
    at processImports ($deno$/compiler.ts:743:31)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)

`$ deno --version
deno 1.0.0-rc3
v8 8.4.300
typescript 3.8.3`

**Comment by Caesar2011** [comment]
Error is known. Will be fixed tomorrow.

**Comment by Caesar2011** [comment]
It is fixed in `https://deno.land/x/denotrain@v0.4.0/mod.ts`.
