### ISSUE TITLE
readme example doesn't run correctly on windows

### ISSUE THREAD

**Issue by Ragzouken** [Caesar2011/denotrain#4]
```
PS C:\Users\mark\Documents\PROJECTS\deno-test> deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

```
PS C:\Users\mark\Documents\PROJECTS\deno-test> deno run --allow-net=127.0.0.1 https://deno.land/x/denotrain@v0.4.0/example/routers/example.ts
Download https://deno.land/x/denotrain@v0.4.0/example/routers/example.ts
Compile https://deno.land/x/denotrain@v0.4.0/example/routers/example.ts
error: Uncaught PermissionDenied: network access to "0.0.0.0:3001", run again with the --allow-net flag
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listen ($deno$/ops/net.ts:51:10)
    at listen ($deno$/net.ts:152:22)
    at serve (https://deno.land/std@0.50.0/http/server.ts:261:20)
    at Application.run (https://deno.land/x/denotrain@v0.4.0/Application.ts:29:15)
    at https://deno.land/x/denotrain@v0.4.0/example/routers/example.ts:41:11
```

**Comment by Caesar2011** [comment]
Fixed in v0.4.1. Now you can specify the hostname beside the port in the app parameters (defaults now to 0.0.0.0). Deno changed the default hostname from 127.0.0.1 to 0.0.0.0 in the final realease v1.0.0 which caused this issue. Thanks for reporting.
